### ISSUE TITLE
License for project

### ISSUE THREAD

**Issue by TheEvilPenguin** [SparkyTD/UnrealEngine.Gvas#4]
Hi,

I was wondering if you'd be willing to attach a license to the code and/or release a build on nuget? I'm working on a project for Railroads Online which this would be quite useful for.

Thanks

**Comment by SparkyTD** [comment]
I added the Apache 2.0 to the project.

Keep in mind that I don't have much time to work on it nowadays, so I might not be able to provide support or respond to issues. I can still accept PRs if you can fix something yourself.

**Comment by TheEvilPenguin** [comment]
Cheers.

No worries about support - I'm more than happy to do PRs if I come across anything in the games implementation that would be a good fit for the generic library though.
